# Generated by Django 2.0.7 on 2018-07-24 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180724_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatter', to=settings.AUTH_USER_MODEL),
        ),
    ]
