# Generated by Django 2.0.7 on 2018-07-25 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180724_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_room',
            new_name='chatroom',
        ),
    ]
