# Generated by Django 2.0.7 on 2018-07-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180725_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatter',
            name='fcm_reg_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
